/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.exe1;

/**
 *
 * @author daniel.pires
 */
public class TestaTela extends javax.swing.JFrame {

    /**
     * Creates new form TestaTela
     */
    public TestaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        animal = new javax.swing.JRadioButton();
        passaro = new javax.swing.JRadioButton();
        bemtevi = new javax.swing.JRadioButton();
        papagaio = new javax.swing.JRadioButton();
        mamifero = new javax.swing.JRadioButton();
        cachorro = new javax.swing.JRadioButton();
        vaca = new javax.swing.JRadioButton();
        jLabel = new javax.swing.JLabel();
        vocabulario = new javax.swing.JTextField();
        lateMuito = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Sistema de Zoológico");

        jLabel2.setText("Nome do Animal");

        jLabel3.setText("Tipo");

        buttonGroup1.add(animal);
        animal.setSelected(true);
        animal.setText("Animal");

        buttonGroup1.add(passaro);
        passaro.setText("Pássaro");

        buttonGroup1.add(bemtevi);
        bemtevi.setText("Bem Te Vi");

        buttonGroup1.add(papagaio);
        papagaio.setText("Papagaio");

        buttonGroup1.add(mamifero);
        mamifero.setText("Mamífero");

        buttonGroup1.add(cachorro);
        cachorro.setText("Cachorro");

        buttonGroup1.add(vaca);
        vaca.setText("Vaca");

        jLabel.setText("Vocabulário");

        lateMuito.setText("Late Muito");

        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(animal)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passaro)
                            .addComponent(bemtevi)
                            .addComponent(mamifero)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(papagaio)
                                    .addComponent(cachorro)
                                    .addComponent(vaca)
                                    .addComponent(jButton1))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lateMuito)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel)
                                        .addGap(37, 37, 37)
                                        .addComponent(vocabulario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(animal))
                .addGap(18, 18, 18)
                .addComponent(passaro)
                .addGap(18, 18, 18)
                .addComponent(bemtevi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papagaio)
                    .addComponent(jLabel)
                    .addComponent(vocabulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mamifero)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cachorro)
                    .addComponent(lateMuito))
                .addGap(18, 18, 18)
                .addComponent(vaca)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void polimorfico(Animal camaleao){
        resultado.setText(camaleao.toString() + " " + camaleao.fala());
    }
            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = nome.getText();
        if (animal.isSelected()){
            Animal objAnimal = new Animal(name); 
            polimorfico(objAnimal);
        }
        else if (passaro.isSelected()){
              Passaro objPassaro = new Passaro(name); 
              polimorfico(objPassaro);
            }
            else if (bemtevi.isSelected()){
                    BemTeVi objBemTeVi = new BemTeVi(name); 
                    polimorfico(objBemTeVi);
                 }
                 else if (papagaio.isSelected()){
                        Papagaio objPapagaio = new Papagaio(name, vocabulario.getText()); 
                        polimorfico(objPapagaio);
                    }
                    else if (mamifero.isSelected()){
                            Mamifero objMamifero = new Mamifero(name); 
                            polimorfico(objMamifero);
                         }
                         else if (cachorro.isSelected()){
                                Cachorro objCachorro = new Cachorro(lateMuito.isSelected(), name); 
                                polimorfico(objCachorro);
                            }
                            else {
                                 Vaca objVaca = new Vaca(name); 
                                    polimorfico(objVaca);
                             }    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton animal;
    private javax.swing.JRadioButton bemtevi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cachorro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lateMuito;
    private javax.swing.JRadioButton mamifero;
    private javax.swing.JTextField nome;
    private javax.swing.JRadioButton papagaio;
    private javax.swing.JRadioButton passaro;
    private javax.swing.JTextArea resultado;
    private javax.swing.JRadioButton vaca;
    private javax.swing.JTextField vocabulario;
    // End of variables declaration//GEN-END:variables
}
